#!/usr/bin/env bash
# =============================================================================
# Tally & Trace – Supabase Setup Helper
# =============================================================================
# Prerequisites:
#   - Supabase CLI installed: https://supabase.com/docs/guides/cli
#   - supabase login (already authenticated)
#
# Usage:
#   chmod +x scripts/setup-supabase.sh
#   ./scripts/setup-supabase.sh [project-ref]
# =============================================================================

set -euo pipefail

PROJECT_REF="${1:-}"
REGION="ap-southeast-1"   # Singapore – closest to PH

# ---------------------------------------------------------------------------
# 1. Validate args
# ---------------------------------------------------------------------------
if [[ -z "$PROJECT_REF" ]]; then
  echo "Usage: $0 <supabase-project-ref>"
  echo "  You can find the project ref on the Supabase dashboard → Project Settings."
  exit 1
fi

# ---------------------------------------------------------------------------
# 2. Fetch the connection string and write .env
# ---------------------------------------------------------------------------
echo "Fetching connection details for project: $PROJECT_REF …"
DB_URL=$(supabase db remote connection-string --project-ref "$PROJECT_REF" 2>/dev/null \
         || echo "")

if [[ -z "$DB_URL" ]]; then
  echo ""
  echo "⚠️  Could not auto-fetch connection string."
  echo "   Go to: https://app.supabase.com/project/$PROJECT_REF/settings/database"
  echo "   Copy 'Connection string (URI)' and paste it below:"
  read -rp "DATABASE_URL: " DB_URL
fi

ENV_FILE="backend/.env"
if [[ -f "$ENV_FILE" ]]; then
  echo "Backing up existing $ENV_FILE → ${ENV_FILE}.bak"
  cp "$ENV_FILE" "${ENV_FILE}.bak"
fi

cat > "$ENV_FILE" <<EOF
# Tally & Trace – Environment Variables (generated by setup-supabase.sh)
DATABASE_URL=${DB_URL}
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
ENVIRONMENT=development
DEBUG=true
BACKEND_CORS_ORIGINS_STR=http://localhost:3000,http://localhost:8000

# Resend (transactional email via hello@studiosc.dev)
RESEND_API_KEY=
RESEND_FROM_EMAIL=hello@studiosc.dev

# Frontend URL (used in email links)
FRONTEND_BASE_URL=http://localhost:3000
EOF

echo ""
echo "✅  backend/.env written with Supabase DATABASE_URL."
echo ""

# ---------------------------------------------------------------------------
# 3. Run Alembic migrations
# ---------------------------------------------------------------------------
echo "Running Alembic migrations …"
cd backend
alembic upgrade head
cd ..

echo ""
echo "✅  Migrations applied."
echo ""
echo "Next steps:"
echo "  1. Fill in RESEND_API_KEY in backend/.env"
echo "  2. Start the backend:  cd backend && uvicorn app.main:app --reload"
echo "  3. Start the frontend: cd frontend && pnpm dev"
